### PR TITLE
Update download-monitor-fa_IR.po

### PR DESCRIPTION
**Pull request by Li-An**
updated french po

### CODE REVIEW

**Comment by barrykooij** [comment]
Hey @Li-An! Thanks for taking the time to update the translation. Looks like you saved it as the wrong file though, the fa_IR file contains the Persian translation. Could you please update the fr_FR files?

**Comment by Li-An** [comment]
It seems I cannot update mo file ? Can I send you them to your email ?

**Comment by barrykooij** [comment]
sure, shoot me an email at git@barrykooij.nl

**Comment by barrykooij** [comment]
I've updated the French documentation on Transifex. It's at 92% now, you can help with the remaining strings here if you want to: https://www.transifex.com/projects/p/download-monitor/translate/#fr_FR/download-monitorpot

Thank you!

**Pull request closed without merging**
