### PR TITLE
Enable users to specify a custom template dir

### PR DESCRIPTION
**Pull request by mdmower**
3rd party extensions take precedence.

### CODE REVIEW

**Comment by mdmower** [comment]
I'm not particularly proud of how this one is implemented. For one, it should probably only be visible if Custom is selected as the template. Second, it should not piggy-back the existing custom_dir implementation, but provide its own. Let me know if you have some preferred design choices that would affect this. I can also be reached on Freenode IRC as user mdmower.

**Comment by barrykooij** [comment]
I like the idea of this but I'm not sure adding an option is the right way to solve this issue. I think I'd rather see this solved with a new filter.

If you're comfortable enough with coding that you want a custom template directory you're probably comfortable enough to add a filter.

**Comment by mdmower** [comment]
Commit updated. Adds template_dir as an attribute to shortcodes. What do you think of this approach?

**Comment by mdmower** [comment]
Commit updated based on @dannyvankooten comment to use is_dir(). Unfortunately, my force-push killed that comment (sorry about that). Thanks for the suggestion.

**Comment by mdmower** [comment]
I force-pushed to dev3 to resolve the merge conflict with recent commits to master.

**Comment by mdmower** [comment]
Is it safe to assume this won't be merged? If so, I'd prefer to close it.

**Comment by barrykooij** [comment]
No, we have this planned for the 4.0 release :)

**Comment by mdmower** [comment]
1.5 yrs simply isn't reasonable. I'm sure you can implement this on your own if you ever decide it's worth including.

**Comment by barrykooij** [comment]
I understand if you don't want to work on this PR anymore but please keep it open so I can merge it in 4.0 :+1:

**Comment by barrykooij** [comment]
With the current direction the 4.0 release is going I've decided to not include this for now. I'm sorry for the long wait on this.

**Pull request closed without merging**
