### PR TITLE
Add option for unique-IP-only dl counter increment

### PR DESCRIPTION
**Pull request by mdmower**
Introduce a new option 'Count unique IPs only' that limits
incrementing of each download counter to unique IP addresses.

### CODE REVIEW

**Comment by mdmower** [comment]
Test site with feature enabled: http://wptest.cmphys.com

**Comment by mdmower** [comment]
I pushed a new revision just now that addresses an issue if the log table is empty. This could still use some more testing; I will report back later if more changes are needed.

**Comment by mdmower** [comment]
It only dawned on me tonight that logging can actually be disabled in download monitor, and this option relies on logging to function. So, this option has been moved to the Logging tab and is hidden when logging is disabled. Similarly, a check is performed in-code to ensure logging is enabled before attempting to use the feature.

**Comment by barrykooij** [comment]
@mdmower PR looks good so far. Planning to merge this into the 1.8.0 release.
Small idea I want to run by you. What do you think making this an unique download per day? So it prevents 'spam' by download manager but will still increment downloads from e.g. public places.

**Comment by mdmower** [comment]
Feel free to amend as you best see the option incorporated. User feedback will let you know how to tweak it going forward. I am away from any coding computer until July 8th or so. So, its up to you how you would like to manage this for now.

**Comment by barrykooij** [comment]
@mdmower Alright, I'll go and make that tweak and see how people will react to it. 
By the way, I didn't mean for you to change it. I just wanted to get your opinion on it :)

**Comment by barrykooij** [comment]
working in this at the moment: https://github.com/download-monitor/download-monitor/tree/pr/276

**Pull request merged**
