### PR TITLE
Add setting which can allow downloads to be surfaced in site search. Also, make it so the permalink redirects to the download.

### PR DESCRIPTION
**Pull request by KZeni**
I have a site which uses Algolia.com for its site search (though other site search setups would be affected as well!), and I wanted the downloads to be surfaced via that search. Currently (as of version 1.9.7), **the dlm_download post type is excluded from WordPress' site search without any way to change this**. As such, I've made it so there's now an option for enabling/disabling search visibility of downloads & made the resulting links go to the corresponding download URL.

# What was done
I've added an option to the Download settings page (a single checkbox under the general tab) which makes it possible to enable search for download on a site. This checkbox effectively toggles the `public`, `publicly_queryable`, `exclude_from_search`, and `query_var` values accordingly for the `dlm_download post type`. Then, I had to make it so there was a single post type template so I can act on the query_vars based on the download's permalink (which doesn't actually match the download's URL.) Finally, I made that single post type template use the query_vars to redirect to the correct download.

As an aside, I also went in and added labels to the `dlm_download_version` post type since many plugins which interface with the post types on a site show this as "Posts" as the fallback label, and that's confusing & simply incorrect (adding the labels was a minor change).

# Wrap-up
This functionality is important for a site I'm working on, and I imagine there's plenty of others out there that would love to have their site search able to return the downloads on their site (while keeping it as an option for those that don't).

I would love to see this added in a future release of the plugin so I don't have to worry about this important feature being removed when I update the plugin. Thanks for the great plugin!

### CODE REVIEW

**Comment by barrykooij** [comment]
This looks very promising. Will look into merging this in 4.0 release.

**Comment by KZeni** [comment]
Alright, I've updated this PR so that the download URL that's surfaced via search results (and elsewhere on the site) is now set up so the post type rewrite checks for the current endpoint setting via the plugin's options and acts accordingly (meaning having a custom-set slug via the Download Monitor settings will result in the search results using that same exact URL.)

**Comment by KZeni** [comment]
Ah, so I had to make it so the rewrite slug wasn't exactly matching the slug endpoint set via the plugin's settings. It would cause a redirect loop if the two were the same. I'm wondering if the URL endpoint handling could be reworked to make it so the internal rewrite for the downloads could match the endpoint set via the settings. For now, I've set it up so it uses the defined slug in settings with '-link' appended to the end to make it unique (preventing redirect loop conflict) while making it a little more friendly of a URL.

**Comment by KZeni** [comment]
As an aside, this still works with the latest version of Download Monitor

I had to re-patch my site with this since I have it auto-update to the latest version of plugins. It'd be nice if this were to be implemented before the next version so I don't have to keep an eye out for new versions and needing to re-patch this each time to fix the fact that the new version broke this.

Seems like this would provide a nice foothold for this feature to be more thoroughly integrated without any downsides of having it be implemented before version 4, but ultimately it's not my decision.

**Comment by barrykooij** [comment]
> Seems like this would provide a nice foothold for this feature to be more thoroughly integrated without any downsides of having it be implemented before version 4, but ultimately it's not my decision.
Since it's a new feature it can only be added in a major release (a Y release so to so). The 4.0 release just happens to be the next major release.

**Comment by barrykooij** [comment]
The `4.0` branch is currently still in active development and at it's current state isn't fully working. It would be great however if this PR could be targetted at that branch since it contains a lot of changes compared to master. It's probably good to wait until the `4.0` branch is in a more stable state, say a beta1 moment.

**Comment by barrykooij** [comment]
Changed target to `4.0`. Surprise, can't be auto-merged :)
Will look into this later.

**Comment by barrykooij** [comment]
Merged via #442

**Pull request merged**
