### PR TITLE
Handle logging/counting functionality in log()

### PR DESCRIPTION
**Pull request by mdmower**
The current implementation of the wp_dlm_downloading cookie cooldown
only applies to download counts. This can lead to inconsistencies
between the number of log entries created and the number of downloads
counted. Expand the functionality of log() (which can be renamed later
if desired) to:

* Perform 60sec wp_dlm_downloading cookie cooldown test and set
* Write log and increment download count based on unique IP option (if
  logging is enabled)

This brings back the original intention of the cookie cooldown to
reduce redundant entries in the log for ill-behaved download managers
and anxious clickers.

### CODE REVIEW

**Comment by mdmower** [comment]
This definitely needs a review (I'm at work and cannot test for another 6-7 hrs), but I think this is a more appropriate way to utilize the cookie feature. Thoughts?

**Comment by barrykooij** [comment]
This is great, I was going to work on something very similar today.

I agree that the total checks should be in one place.

**Comment by barrykooij** [comment]
Alright, so I check with Mike about the original intent of the log and it's an access log. This means that it's currently working as it should. The cookie cooldown should stop the download counter from incrementing but the log entries should be created anyway. We might want to look at ill-behaved download managers seperatly but anxious clickers should be logged.

**Comment by mdmower** [comment]
Ok, I think I have an alternative in mind. Instead of using the cookie for a log cooldown, a new column in the log page can be created: "Access attempts". Then, when a download is triggered, a comparison can be make to the immediately previous log entry to see if it matches (aside from time). If so, then the "Access attempts" can simply be incremented by 1 instead of creating a new log line. For old entries where "Access attempts" is undefined, the log viewer would by default show 1.

This would resolve the issue reported here: https://wordpress.org/support/topic/lots-of-downloads-with-ie-70windows-8-user-agent

**Comment by barrykooij** [comment]
That issue would also be solved with the new unique IP download count option right? I want to keep the log as pure as possible as it should represent a raw access log of the downloads.

**Pull request closed without merging**
